/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas1;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class tpsv1 extends javax.swing.JFrame {

    /**
     * Creates new form tpsv1
     */
    public tpsv1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupkelas = new javax.swing.ButtonGroup();
        grupjurusan = new javax.swing.ButtonGroup();
        panelbiasa = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        jurusan = new javax.swing.JLabel();
        rbti = new javax.swing.JRadioButton();
        kelas = new javax.swing.JLabel();
        cba = new javax.swing.JCheckBox();
        cbb = new javax.swing.JCheckBox();
        cbc = new javax.swing.JCheckBox();
        cbd = new javax.swing.JCheckBox();
        cbe = new javax.swing.JCheckBox();
        tfnama = new javax.swing.JTextField();
        tfnim = new javax.swing.JTextField();
        rbilkom = new javax.swing.JRadioButton();
        jeniskelamin = new javax.swing.JLabel();
        cbjl = new javax.swing.JComboBox<>();
        RESET = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelbiasa.setBackground(new java.awt.Color(255, 0, 0));

        nama.setText("NAMA");

        nim.setText("NIM");

        jurusan.setText("JURUSAN");

        grupjurusan.add(rbti);
        rbti.setText("Ti");
        rbti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtiActionPerformed(evt);
            }
        });

        kelas.setText("KELAS");

        grupkelas.add(cba);
        cba.setText("A2015");

        grupkelas.add(cbb);
        cbb.setText("B2015");

        grupkelas.add(cbc);
        cbc.setText("C2015");

        grupkelas.add(cbd);
        cbd.setText("D2015");

        grupkelas.add(cbe);
        cbe.setText("E2015");

        tfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnamaActionPerformed(evt);
            }
        });

        grupjurusan.add(rbilkom);
        rbilkom.setText("ILKOM");

        jeniskelamin.setText("JENIS KELAMIN");

        cbjl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan", "lainya" }));
        cbjl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjlActionPerformed(evt);
            }
        });

        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        bsimpan.setText("SIMPAN");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelbiasaLayout = new javax.swing.GroupLayout(panelbiasa);
        panelbiasa.setLayout(panelbiasaLayout);
        panelbiasaLayout.setHorizontalGroup(
            panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbiasaLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbiasaLayout.createSequentialGroup()
                        .addComponent(rbti)
                        .addGap(68, 68, 68)
                        .addComponent(rbilkom))
                    .addGroup(panelbiasaLayout.createSequentialGroup()
                        .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nim)
                            .addComponent(nama))
                        .addGap(38, 38, 38)
                        .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfnim, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jeniskelamin)
                            .addComponent(cbjl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelbiasaLayout.createSequentialGroup()
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelbiasaLayout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(jurusan))
                        .addGroup(panelbiasaLayout.createSequentialGroup()
                            .addGap(130, 130, 130)
                            .addComponent(kelas))
                        .addGroup(panelbiasaLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cba)
                            .addGap(18, 18, 18)
                            .addComponent(cbb)
                            .addGap(18, 18, 18)
                            .addComponent(cbc)
                            .addGap(29, 29, 29)
                            .addComponent(cbd)
                            .addGap(18, 18, 18)
                            .addComponent(cbe)))
                    .addGroup(panelbiasaLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(bsimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RESET)
                        .addGap(42, 42, 42)
                        .addComponent(EXIT)
                        .addGap(47, 47, 47)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        panelbiasaLayout.setVerticalGroup(
            panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelbiasaLayout.createSequentialGroup()
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelbiasaLayout.createSequentialGroup()
                        .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelbiasaLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nama)
                                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelbiasaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jeniskelamin)))
                        .addGap(18, 18, 18)
                        .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nim)
                            .addComponent(tfnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cbjl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jurusan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbti)
                    .addComponent(rbilkom))
                .addGap(18, 18, 18)
                .addComponent(kelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cba)
                    .addComponent(cbb)
                    .addComponent(cbc)
                    .addComponent(cbd)
                    .addComponent(cbe))
                .addGap(38, 38, 38)
                .addGroup(panelbiasaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RESET)
                    .addComponent(EXIT)
                    .addComponent(bsimpan))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelbiasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelbiasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnamaActionPerformed

    private void rbtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtiActionPerformed

    private void cbjlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjlActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
tfnama.setText("");
tfnim.setText("");

    }//GEN-LAST:event_formWindowOpened

    
    
    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        tfnama.setText("");
        tfnim.setText("");
        cbjl.setSelectedIndex(0);
        grupjurusan.clearSelection();
        grupkelas.clearSelection();
        
        
    }//GEN-LAST:event_RESETActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
String jenkel =(String)cbjl.getSelectedItem();
String jurusan="";
if(rbti.isSelected()) {
        jurusan = rbti.getText();
    }else{
        jurusan=rbilkom.getText();
}
String kelas="";
if(cba.isSelected()) {
        kelas = cba.getText();
    }else if(cbb.isSelected()){
        kelas = cbb.getText();
}
    else if(cbc.isSelected()){
    kelas = cbc.getText();
    }else if(cbd.isSelected()){
    kelas = cbd.getText();
    }else{
        kelas=cbe.getText();
    }
String nama = tfnama.getText();
String nim =tfnim.getText();
JOptionPane.showMessageDialog(this,nama+"\n"+nim+"\n"+jenkel+"\n"+jurusan+"\n"+kelas);        // TODO add your handling code here:
    }//GEN-LAST:event_bsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tpsv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tpsv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tpsv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tpsv1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tpsv1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton RESET;
    private javax.swing.JButton bsimpan;
    private javax.swing.JCheckBox cba;
    private javax.swing.JCheckBox cbb;
    private javax.swing.JCheckBox cbc;
    private javax.swing.JCheckBox cbd;
    private javax.swing.JCheckBox cbe;
    private javax.swing.JComboBox<String> cbjl;
    private javax.swing.ButtonGroup grupjurusan;
    private javax.swing.ButtonGroup grupkelas;
    private javax.swing.JLabel jeniskelamin;
    private javax.swing.JLabel jurusan;
    private javax.swing.JLabel kelas;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nim;
    private javax.swing.JPanel panelbiasa;
    private javax.swing.JRadioButton rbilkom;
    private javax.swing.JRadioButton rbti;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnim;
    // End of variables declaration//GEN-END:variables
}
